### PR TITLE
Added Bug Report Sticky Footer

### LINKED ISSUE #128: Add Bug Report Banner

### PR DESCRIPTION
**Pull request by rymaju**
## Issue

Closes #128 

## Changes

- Added a footer to the site that links to the LLB bug report form

## Screenshots

image

And its sticky too! (plus a little translucent)

image

### CODE REVIEW

File: src/components/BugReportFooter.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import { BugOutlined } from '@ant-design/icons';
+import { Typography } from 'antd';
+import React from 'react';
+import styled from 'styled-components';
+const { Text, Link } = Typography;
+const LittleBugIcon = styled(BugOutlined)`
```
Comment (anirudh723) [inline src/components/BugReportFooter.tsx:6]: Could do an extra space to separate the styled components stuff

**Review by anirudh723 — APPROVED** [review]
LGTM 👍

**Review by onb6 — APPROVED** [review]
I feel like the text could be a little smaller, its a tiny bit distracting, but otherwise its good!
